In [399]:
import numpy as np

In [400]:
data1 = [6,7.5,8,0,1]
data1

[6, 7.5, 8, 0, 1]

In [401]:
# numpy를 이용하여 1차원 1배열로 변형하기
# 7.5가 포함됨으로 전부 실수형 array로 변형됨
arr1 = np.array(data1)
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [402]:
# 배열의 크기 확인하기 (shape)
# 괄호 없음 주의
arr1.shape

(5,)

### 2차원

In [403]:
data2 = [
    [1,2,3,4],
    [5,6,7,8]
]
data2

[[1, 2, 3, 4], [5, 6, 7, 8]]

In [404]:
arr2 = np.array(data2)
arr2
# 차원, 배열로 변형함으로써 가독성이 올라간다

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [405]:
arr2.shape
# 2행 4열의 배열임을 쉽게 확인

(2, 4)

In [406]:
# 0으로 구성된 1차원 배열 생성
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [407]:
# 0으로 구성된 5행 2열의 3차원 배열 생성
np.zeros([3, 5, 2])
# [page, row, column]

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [408]:
np.zeros([2, 3, 5, 2])
# (0으로 구성된 5행 2열의 3차원 배열 생성) 이 2개 (=4차원)

array([[[[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]]]])

In [409]:
# 1로만 구성된 배열 생성
np.ones(5)

array([1., 1., 1., 1., 1.])

In [410]:
# 10으로 구성된 배열 생성 (full)
np.full(5,10)
# 10이 다섯개

array([10, 10, 10, 10, 10])

- 이미지를 감지하는 딥러닝 모델 만들 경우
- 이미지 사이즈가 전부 다르므로 여백을 채워줘야 함 (full 사용)

In [411]:
# 0으로 구성된 3행 5열 배열 생성
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [412]:
# 8로 구성된 3행 5열 배열 생성 (full 사용)
np.full((3,5),8)

array([[8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8]])

In [413]:
# 범위가 있는 배열 (arange)
np.arange(10,15)

array([10, 11, 12, 13, 14])

In [414]:
# 정수형으로 이루어진 배열 -> 실수형으로 변환
arr = np.array([1,2,3,4,5],dtype=np.int64)
arr
arr.dtype

dtype('int64')

In [415]:
float_arr = arr.astype(np.float64)
float_arr
float_arr.dtype

dtype('float64')

### 행렬 연산

In [416]:
arr1 = np.array([
    [1,2,3],
    [4,5,6]
])
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [417]:
arr2 = np.array([
    [7,8,9],
    [10,11,12]
])
arr2

array([[ 7,  8,  9],
       [10, 11, 12]])

In [418]:
arr1 + arr2

array([[ 8, 10, 12],
       [14, 16, 18]])

In [419]:
arr1 - arr2

array([[-6, -6, -6],
       [-6, -6, -6]])

In [420]:
arr1 * arr2

array([[ 7, 16, 27],
       [40, 55, 72]])

In [421]:
np.sqrt(arr1)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [422]:
1 / arr1 # 역수

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [423]:
(1 / arr1) * arr1

array([[1., 1., 1.],
       [1., 1., 1.]])

In [424]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [425]:
arr[5:9]

array([5, 6, 7, 8])

In [426]:
arr[5:9] = 12
arr
# 손상된 이미지 복원 등에 사용

array([ 0,  1,  2,  3,  4, 12, 12, 12, 12,  9])

In [427]:
arr[:5]

array([0, 1, 2, 3, 4])

In [428]:
arr[8:]

array([12,  9])

### 2차원 배열

In [429]:
arr2d = np.array([
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12],
    [13,14,15,16]
])
arr2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [430]:
# 2번 행의 자료 출력
arr2d[2,:]

array([ 9, 10, 11, 12])

In [431]:
# 1에서 2번 행의 자료 출력
arr2d[1:3,:]

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [432]:
# 3번 열의 자료 출력
arr2d[:,3]

array([ 4,  8, 12, 16])

In [433]:
# 0,1열의 자료 출력
arr2d[:,0:2]

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10],
       [13, 14]])

In [434]:
# 1행 2열의 자료 출력
arr2d[1,2]

7

In [435]:
arr2d[0:2,1:3] = 0 # <- 차원축소
arr2d

array([[ 1,  0,  0,  4],
       [ 5,  0,  0,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

- Train, Test
- Python에서는 Valid Data가 추가된다.
- 과대적합 (over fitting) (모델이 train set에 과대하게 적합되어 일반성; General Performance가 떨어지는 현상이 일어날 수 있다.)
- 과소 적합(under fitting)은 반대로 모델이 훈련 세트의 규칙을 제대로 찾지 못해 모델의 성능이 낮게 나오는 현상
- 이를 방지하기 위해 training data를 training, validation으로 나눈다. <= 차원축소 (미분)
- Test data 외의 새로운 data에서도 잘 작동할지를 알기 위해 valid data를 사용한다.
- ex. train data = 표준어 학습, valid data = 새로운 사투리 데이터 => 재학습

### 난수발생
- rand: 0~1사이의 균일 분포
- randn: 가우시안 표준 정규분포
- randint: 균일분포의 정수 난수

In [436]:
# 1차원 이름 배열 생성
names = np.array([
    "Charles",
    "Kenny",
    "Hayoung",
    "Charles",
    "Hayoung",
    "Kenny",
    "Kenny"
])
names

array(['Charles', 'Kenny', 'Hayoung', 'Charles', 'Hayoung', 'Kenny',
       'Kenny'], dtype='<U7')

In [437]:
# 7행 4열의 난수 데이터 생성
data = np.random.randn(7,4)
data

array([[-0.08843551, -1.00244992, -1.12195372, -0.63681406],
       [-1.06930003,  1.10252359,  1.23512147, -1.24119889],
       [ 0.86790799,  0.98875278,  0.37331141,  0.49476119],
       [ 0.63697828,  1.81404473,  0.24006831, -0.28092977],
       [-0.22498076,  1.83941291, -0.67760289,  2.2147277 ],
       [-0.19922932, -0.00538967, -0.89246038, -0.4641347 ],
       [ 0.40044206, -0.0409942 , -0.61630421,  0.98622638]])

In [438]:
# Mask
names == "Charles"

array([ True, False, False,  True, False, False, False])

In [439]:
data[names == 'Charles',:] # True에 해당하는 행 출력

array([[-0.08843551, -1.00244992, -1.12195372, -0.63681406],
       [ 0.63697828,  1.81404473,  0.24006831, -0.28092977]])

In [440]:
data[(names == 'Charles') | (names == 'Kenny'),:]

# 필요한 값을 추출할 때 True/False값을 많이 사용한다.

array([[-0.08843551, -1.00244992, -1.12195372, -0.63681406],
       [-1.06930003,  1.10252359,  1.23512147, -1.24119889],
       [ 0.63697828,  1.81404473,  0.24006831, -0.28092977],
       [-0.19922932, -0.00538967, -0.89246038, -0.4641347 ],
       [ 0.40044206, -0.0409942 , -0.61630421,  0.98622638]])

In [441]:
# data의 4번째 열 값중 0보다 작은 것의 mask 만들기
data[:,3] < 0

array([ True,  True, False,  True, False,  True, False])

In [442]:
data[data[:,3] < 0,:]

array([[-0.08843551, -1.00244992, -1.12195372, -0.63681406],
       [-1.06930003,  1.10252359,  1.23512147, -1.24119889],
       [ 0.63697828,  1.81404473,  0.24006831, -0.28092977],
       [-0.19922932, -0.00538967, -0.89246038, -0.4641347 ]])

In [443]:
# 정렬
arr = np.random.rand(8)
arr

array([0.39779393, 0.10412366, 0.37916347, 0.5111511 , 0.65292612,
       0.82859801, 0.03882375, 0.68294112])

In [444]:
# 오름차순
np.sort(arr)

array([0.03882375, 0.10412366, 0.37916347, 0.39779393, 0.5111511 ,
       0.65292612, 0.68294112, 0.82859801])

In [445]:
# 내림차순
np.sort(arr)[::-1]

# 주의: np.sort(arr)[:-1] <- pop (마지막 제외)

array([0.82859801, 0.68294112, 0.65292612, 0.5111511 , 0.39779393,
       0.37916347, 0.10412366, 0.03882375])

In [446]:
arr = np.random.rand(5,3)
arr

array([[0.55090207, 0.8995549 , 0.51507495],
       [0.13700994, 0.57446775, 0.13429324],
       [0.68116933, 0.46067584, 0.70621409],
       [0.39528469, 0.86178721, 0.33612941],
       [0.23194471, 0.71598098, 0.56103019]])

In [447]:
# 2차원 데이터이므로 정렬 기준을 정해줘야 함
# 열방향 오름차순
np.sort(arr,axis=0)

array([[0.13700994, 0.46067584, 0.13429324],
       [0.23194471, 0.57446775, 0.33612941],
       [0.39528469, 0.71598098, 0.51507495],
       [0.55090207, 0.86178721, 0.56103019],
       [0.68116933, 0.8995549 , 0.70621409]])

In [448]:
# 행방향 오름차순
np.sort(arr,axis=1)

array([[0.51507495, 0.55090207, 0.8995549 ],
       [0.13429324, 0.13700994, 0.57446775],
       [0.46067584, 0.68116933, 0.70621409],
       [0.33612941, 0.39528469, 0.86178721],
       [0.23194471, 0.56103019, 0.71598098]])

---
# reshape
- 데이터 보존하며 차원을 바꿈
- DL에서 매우 중요
- R에서 for문으로 처리했던 과정을 간결하게 도와줌

In [449]:
arr = np.arange(1,9)
arr

array([1, 2, 3, 4, 5, 6, 7, 8])

In [450]:
# 2차원 배열 (2행 4열)로 변경
# np 사용할 때는 np로 생성된 배열만 가능함 주의
# list => np.array로 바꾼 후 작업
arr1 = np.reshape(arr,(2,4))
arr1

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [451]:
# 3차원 배열로 변경
arr2 = np.reshape(arr,(2,2,2))
# page, row, column
arr2

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [452]:
# 2차원 배열을 1차원으로 변경
arr3 = np.reshape(arr1,(-1,1))
arr4 = np.reshape(arr1,(-1))
# 데이터 개수를 정하기 어려운 경우: -1
print(arr3)
print(arr4)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]
[1 2 3 4 5 6 7 8]


- (분석): arr3 = np.reshape(arr1,(-1))
- (딥러닝): arr3 = np.reshape(arr1,(-1,1))

In [453]:
arr3 == arr4

array([[ True, False, False, False, False, False, False, False],
       [False,  True, False, False, False, False, False, False],
       [False, False,  True, False, False, False, False, False],
       [False, False, False,  True, False, False, False, False],
       [False, False, False, False,  True, False, False, False],
       [False, False, False, False, False,  True, False, False],
       [False, False, False, False, False, False,  True, False],
       [False, False, False, False, False, False, False,  True]])

In [454]:
# 3차원 배열을 1차원으로 변경
arr5 = arr2.reshape(-1,1)
arr5

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8]])

In [455]:
arr3 == arr5

array([[ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True]])